import type { InternalPermission, InternalRole } from "@/generated/prisma/client";

export const internalRoleLabels: Record<InternalRole, string> = {
  super_admin: "Super administrador",
  direccion: "Dirección",
  medico: "Médico",
  recepcion: "Recepción",
  captacion: "Captación",
  administracion: "Administración",
  enfermeria: "Enfermería",
  seguimiento: "Seguimiento"
};

/**
 * Rol deprecado por la simplificacion V3.7: no asignar a usuarios nuevos.
 * El valor permanece en el enum de Prisma porque existen filas con ese rol;
 * un usuario con este rol solo conserva `internal_access` hasta ser reasignado
 * (script `pnpm internal:set-role`).
 */
export const deprecatedInternalRoles: InternalRole[] = ["captacion"];

export const internalRolePermissions: Record<InternalRole, InternalPermission[]> = {
  super_admin: [
    "internal_access",
    "patients_read",
    "patients_create",
    "patients_update",
    "visits_read",
    "visits_create",
    "visits_update",
    "patient_route_read",
    "patient_route_update",
    "area_time_write",
    "clinical_read",
    "clinical_write",
    "clinical_finalize",
    "clinical_correct",
    "nursing_read",
    "nursing_write",
    "studies_read",
    "studies_write",
    "sales_read",
    "sales_write",
    "payments_write",
    "cash_sessions_read",
    "cash_sessions_open",
    "cash_movements_create",
    "cash_movements_reverse",
    "cash_sessions_close",
    "cash_sessions_approve",
    "followups_read",
    "followups_write",
    "reminder_rules_manage",
    "reminders_review",
    "inventory_read",
    "inventory_write",
    "inventory_adjust",
    "inventory_cost_read",
    "suppliers_read",
    "suppliers_write",
    "purchases_read",
    "purchases_write",
    "purchase_receipts_write",
    "inventory_lot_adjust",
    "reports_read",
    "audit_read",
    "users_manage",
    "attachments_read",
    "attachments_write",
    "attachments_delete",
    "patient_consents_read",
    "patient_consents_write",
    "attribution_manage",
    "patient_duplicates_read",
    "patient_duplicates_review",
    "patient_duplicates_merge",
    "visit_discontinuations_read",
    "visit_discontinuations_write",
    "documents_configure"
  ],
  direccion: [
    "internal_access",
    "patients_read",
    "visits_read",
    "patient_route_read",
    "clinical_read",
    "nursing_read",
    "studies_read",
    "sales_read",
    "cash_sessions_read",
    "cash_movements_reverse",
    "cash_sessions_approve",
    "followups_read",
    "reminder_rules_manage",
    "inventory_read",
    "inventory_cost_read",
    "suppliers_read",
    "purchases_read",
    "reports_read",
    "audit_read",
    "attachments_read",
    "patient_consents_read",
    "attribution_manage",
    "patient_duplicates_read",
    "visit_discontinuations_read",
    "documents_configure"
  ],
  medico: [
    "internal_access",
    "patients_read",
    "visits_read",
    "visits_update",
    "patient_route_read",
    "patient_route_update",
    "area_time_write",
    "clinical_read",
    "clinical_write",
    "clinical_finalize",
    "clinical_correct",
    "nursing_read",
    "studies_read",
    "attachments_read",
    "attachments_write",
    "followups_read",
    "followups_write",
    "inventory_read",
    "patient_consents_read",
    "visit_discontinuations_read",
    "visit_discontinuations_write"
  ],
  recepcion: [
    "internal_access",
    "patients_read",
    "patients_create",
    "patients_update",
    "visits_read",
    "visits_create",
    "visits_update",
    "patient_route_read",
    "patient_route_update",
    "area_time_write",
    "followups_read",
    "followups_write",
    "reminders_review",
    "patient_consents_read",
    "patient_consents_write",
    "patient_duplicates_read",
    "patient_duplicates_review",
    "visit_discontinuations_read",
    "visit_discontinuations_write"
  ],
  captacion: ["internal_access"],
  administracion: [
    "internal_access",
    "patients_read",
    "visits_read",
    "visits_update",
    "patient_route_read",
    "area_time_write",
    "sales_read",
    "sales_write",
    "payments_write",
    "cash_sessions_read",
    "cash_sessions_open",
    "cash_movements_create",
    "cash_sessions_close",
    "followups_read",
    "followups_write",
    "inventory_read",
    "inventory_write",
    "inventory_cost_read",
    "suppliers_read",
    "suppliers_write",
    "purchases_read",
    "purchases_write",
    "purchase_receipts_write",
    "inventory_lot_adjust",
    "patient_consents_read",
    "visit_discontinuations_read",
    "visit_discontinuations_write"
  ],
  enfermeria: [
    "internal_access",
    "patients_read",
    "visits_read",
    "patient_route_read",
    "area_time_write",
    "nursing_read",
    "nursing_write",
    "studies_read",
    "studies_write",
    "attachments_read",
    "attachments_write",
    "inventory_read",
    "patient_consents_read",
    "visit_discontinuations_read",
    "visit_discontinuations_write"
  ],
  seguimiento: [
    "internal_access",
    "patients_read",
    "followups_read",
    "followups_write",
    "patient_consents_read"
  ]
};

export const assignableInternalRoles = (
  Object.keys(internalRolePermissions) as InternalRole[]
).filter((role) => !deprecatedInternalRoles.includes(role));

export function roleHasPermission(role: InternalRole, permission: InternalPermission) {
  return internalRolePermissions[role].includes(permission);
}
